version: '3.8'

services:
  librechat:
    image: 'ghcr.io/danny-avila/librechat-dev:latest'
    restart: always
    user: '${UID:-1000}:${GID:-1000}'
    environment:
      - HOST=0.0.0.0
      - PORT=3080
      - DOMAIN_CLIENT={{DOMAIN_CLIENT}}
      - DOMAIN_SERVER={{DOMAIN_SERVER}}
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_MASTER_KEY={{SERVICE_PASSWORD_MEILI_MASTER_KEY}}
      - RAG_PORT=8000
      - RAG_API_URL=http://rag_api:8000
      - JWT_SECRET={{SERVICE_PASSWORD_JWT_SECRET}}
      - JWT_REFRESH_SECRET={{SERVICE_PASSWORD_JWT_REFRESH_SECRET}}
      - ALLOW_EMAIL_LOGIN={{ALLOW_EMAIL_LOGIN:-true}}
      - ALLOW_REGISTRATION={{ALLOW_REGISTRATION:-true}}
      - ALLOW_SOCIAL_LOGIN={{ALLOW_SOCIAL_LOGIN:-false}}
      - ALLOW_SOCIAL_REGISTRATION={{ALLOW_SOCIAL_REGISTRATION:-false}}
      - ALLOW_PASSWORD_RESET={{ALLOW_PASSWORD_RESET:-false}}
      - ALLOW_UNVERIFIED_EMAIL_LOGIN={{ALLOW_UNVERIFIED_EMAIL_LOGIN:-true}}
      - SEARCH=true
      - APP_TITLE={{APP_TITLE:-LibreChat}}
      - OPENAI_API_KEY={{OPENAI_API_KEY:-user_provided}}
      - ANTHROPIC_API_KEY={{ANTHROPIC_API_KEY:-user_provided}}
      - GOOGLE_KEY={{GOOGLE_KEY:-user_provided}}
      - BINGAI_TOKEN={{BINGAI_TOKEN:-user_provided}}
    volumes:
      - librechat-api-images:/app/client/public/images
      - librechat-api-logs:/app/api/logs
    labels:
      - coolify.backup=true

  mongodb:
    image: 'mongo:6.0'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME={{SERVICE_USER_MONGO}}
      - MONGO_INITDB_ROOT_PASSWORD={{SERVICE_PASSWORD_MONGO}}
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: ['CMD', 'mongo', '--eval', "db.runCommand('ping').ok"]
      interval: 5s
      timeout: 10s
      retries: 3
    labels:
      - coolify.backup=true

  meilisearch:
    image: 'getmeili/meilisearch:latest'
    restart: always
    environment:
      - MEILI_NO_ANALYTICS={{MEILI_NO_ANALYTICS:-true}}
      - MEILI_ENV=production
      - MEILI_MASTER_KEY={{SERVICE_PASSWORD_MEILI_MASTER_KEY}}
    volumes:
      - meilisearch-data:/meili_data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://127.0.0.1:7700/health']
      interval: 5s
      timeout: 10s
      retries: 3
    labels:
      - coolify.backup=true

  vectordb:
    image: 'ankane/pgvector:latest'
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER={{SERVICE_USER_POSTGRES}}
      - POSTGRES_PASSWORD={{SERVICE_PASSWORD_POSTGRES}}
    volumes:
      - pgdata2:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U {{SERVICE_USER_POSTGRES}} -d vectordb']
      interval: 5s
      timeout: 10s
      retries: 3
    labels:
      - coolify.backup=true

  rag_api:
    image: 'ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest'
    restart: always
    depends_on:
      - vectordb
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=8000
      - OPENAI_API_KEY={{OPENAI_API_KEY:-user_provided}}

volumes:
  librechat-api-images:
  librechat-api-logs:
  mongodb-data:
  meilisearch-data:
  pgdata2:
