services:
  librechat:
    image: ghcr.io/danny-avila/librechat-dev:latest
    restart: always
    user: '1000:1000'
    environment:
      - HOST=0.0.0.0
      - PORT=3080
      - DOMAIN_CLIENT=http://localhost:3080
      - DOMAIN_SERVER=http://localhost:3080
      - SERVICE_FQDN_LIBRECHAT_3080
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${SERVICE_PASSWORD_64_MEILI}
      - RAG_PORT=8000
      - RAG_API_URL=http://rag_api:8000
      - DEBUG_LOGGING=true
      - NO_INDEX=true
      - ALLOW_EMAIL_LOGIN=${ALLOW_EMAIL_LOGIN:-true}
      - ALLOW_REGISTRATION=${ALLOW_REGISTRATION:-true}
      - ALLOW_SOCIAL_LOGIN=${ALLOW_SOCIAL_LOGIN:-false}
      - ALLOW_SOCIAL_REGISTRATION=${ALLOW_SOCIAL_REGISTRATION:-false}
      - ALLOW_PASSWORD_RESET=${ALLOW_PASSWORD_RESET:-false}
      - ALLOW_UNVERIFIED_EMAIL_LOGIN=${ALLOW_UNVERIFIED_EMAIL_LOGIN:-true}
      - JWT_SECRET=${SERVICE_PASSWORD_64_JWT}
      - JWT_REFRESH_SECRET=${SERVICE_PASSWORD_64_JWTREFRESH}
      - CREDS_KEY=${SERVICE_PASSWORD_64_CREDS}
      - CREDS_IV=${SERVICE_PASSWORD_64_CREDSIV}
      - SEARCH=true
      - APP_TITLE=${APP_TITLE:-LibreChat}
      - 'OPENAI_API_KEY=${SERVICE_OPENAI_API_KEY:-user_provided}'
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-user_provided}
      - GOOGLE_KEY=${GOOGLE_KEY:-user_provided}
      - BINGAI_TOKEN=${BINGAI_TOKEN:-user_provided}
      - ASSISTANTS_API_KEY=${ASSISTANTS_API_KEY:-user_provided}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY:-user_provided}
      - GROQ_API_KEY=${GROQ_API_KEY:-user_provided}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY:-user_provided}
      - ANYSCALE_API_KEY=${ANYSCALE_API_KEY:-user_provided}
      - TOGETHERAI_API_KEY=${TOGETHERAI_API_KEY:-user_provided}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-user_provided}
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
      - 'POSTGRES_DB=${POSTGRES_DB:-vectordb}'
    volumes:
      - librechat-api-images:/app/client/public/images
      - librechat-api-logs:/app/api/logs
  mongodb:
    image: 'docker.io/bitnami/mongodb:5.0'
    volumes:
      - 'mongodb-data:/bitnami/mongodb'
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - 'MONGODB_REPLICA_SET_NAME=rs0'
      - 'MONGODB_PORT_NUMBER=27017'
      - 'MONGODB_INITIAL_PRIMARY_HOST=mongodb'
      - 'MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017'
      - 'MONGODB_ADVERTISED_HOSTNAME=mongodb'
      - 'MONGODB_ENABLE_JOURNAL=${MONGODB_ENABLE_JOURNAL:-true}'
      - 'ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD:-yes}'
    healthcheck:
      test: "echo 'db.stats().ok' | mongo localhost:27017/test --quiet"
      interval: 2s
      timeout: 10s
      retries: 15

  meilisearch:
    image: 'getmeili/meilisearch:latest'
    environment:
      - 'MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}'
      - 'MEILI_ENV=production'
      - MEILI_MASTER_KEY=${SERVICE_PASSWORD_64_MEILI}
    volumes:
      - 'meilisearch-data:/meili_data'
    restart: always
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:7700/health'
      interval: 2s
      timeout: 10s
      retries: 15

  postgres:
    image: ankane/pgvector:latest
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB:-vectordb}'
      - POSTGRES_USER=$SERVICE_USER_POSTGRES
      - POSTGRES_PASSWORD=$SERVICE_PASSWORD_POSTGRES
    restart: always
    volumes:
      - 'pg-data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -h localhost -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 5s
      retries: 3

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - DB_HOST=${POSTGRES_DB:-vectordb}
      - DB_USER=$SERVICE_USER_POSTGRES
      - DB_PASSWORD=$SERVICE_PASSWORD_POSTGRES
      - RAG_PORT=8000
      - 'OPENAI_API_KEY=${SERVICE_OPENAI_API_KEY:-user_provided}'
    restart: always
    depends_on:
      - postgres

volumes:
  librechat-api-images:
  librechat-api-logs:
  mongodb-data:
  meilisearch-data:
  pg-data:
